/**
 * Builds the announcer recording script, docs/ANNOUNCER_SCRIPT.md, from the line list in
 * src/content/announcer.ts:
 *
 *   npm run announcer:script
 *
 * A test fails if the checked-in script is out of date.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { AGAINST_SUFFIX, ANNOUNCER, CALLOUT_DIRECTION, type CalloutKind } from '../src/content/announcer';

export const SCRIPT_PATH = fileURLToPath(new URL('../docs/ANNOUNCER_SCRIPT.md', import.meta.url));

/** The order situations appear in the script: biggest moments first. */
const ORDER: CalloutKind[] = [
  'goal',
  'overtimeWinner',
  'save',
  'wardBlock',
  'bigHit',
  'pileup',
  'turnover',
  'shotClock',
  'crease',
];

const TITLES: Record<CalloutKind, string> = {
  goal: 'Goal',
  overtimeWinner: 'Overtime winner',
  save: 'Save',
  wardBlock: 'Ward block',
  bigHit: 'Big hit',
  pileup: 'Pile-up',
  turnover: 'Turnover',
  shotClock: 'Shot clock violation',
  crease: 'Crease violation',
};

export function renderScript(): string {
  const total = ORDER.reduce((n, k) => n + ANNOUNCER[k].length, 0);
  const out: string[] = [
    '# Spellstick announcer: recording script',
    '',
    '<!-- Generated by `npm run announcer:script` from src/content/announcer.ts. Edit the lines there, not here. -->',
    '',
    `${total} lines, each recorded twice: ${total * 2} files. The game picks a line when the moment happens and shows it as text at the bottom of the screen; if there's a recording for it, it's spoken too.`,
    '',
    "The announcer is a home announcer for the player's team. Each line has a regular take, used when the moment favors the player's team, and an **angry take** (`<id>-against.mp3`), used when it favors the opponent: they score, their goalie robs you, they flatten one of yours, you blow the shot clock. Same words, different read. If a line has no angry take yet, the regular one plays.",
    '',
    '## The voice',
    '',
    '- An arena announcer for a brutal, magical sport played by witches: big, warm, a little theatrical, having the time of their life.',
    '- Short and punchy. Most lines should be under 1.5 seconds, none over about 3. Lines can cut each other off, so a quick read beats a long build.',
    '- Read each line as written. The witch-flavored exclamations are from the Warlock books; say them like set phrases: "Child\'s Tantrum!", "Crone\'s Corns!", "Third-witch in!".',
    '- Record two or three takes of anything you like and pick the best; only one file per id goes in.',
    '',
    '## Files',
    '',
    '- Two files per line: `<id>.mp3` and `<id>-against.mp3` (`.ogg` and `.wav` also work), for example `goal-01.mp3` and `goal-01-against.mp3`.',
    '- Put them in `src/content/announcer-voice/`, commit, and push. Lines without a file stay text-only, so you can add them a few at a time.',
    '- Mono, 44.1 or 48 kHz, MP3 at 96–128 kbps. Trim tight (no more than about 50 ms of silence at either end). Peaks around −1 dBFS, and keep all lines at a similar loudness.',
    '- If you use a text-to-speech service, paste the delivery note for each take as the voice direction. (`npm run announcer:voice` does this with ElevenLabs.)',
  ];
  for (const kind of ORDER) {
    const dir = CALLOUT_DIRECTION[kind];
    out.push(
      '',
      `## ${TITLES[kind]}`,
      '',
      `**When:** ${dir.when}  `,
      `**Regular take:** ${dir.delivery}  `,
      `**Angry take:** ${dir.against}`,
      '',
      '| Line | Regular take | Angry take |',
      '| --- | --- | --- |',
      ...ANNOUNCER[kind].map((l) => `| ${l.text} | \`${l.id}.mp3\` | \`${l.id}${AGAINST_SUFFIX}.mp3\` |`),
    );
  }
  return out.join('\n') + '\n';
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(SCRIPT_PATH, renderScript());
  console.log(`Wrote ${SCRIPT_PATH}`);
}
